export const ELEMENT = [
  ["Blink Overview", "What is Blink", "The Story of Payments"],
  ["open Banking", "Credit/Debit Card", "Direct Debit"],
  [
    "physical Terminal",
    "Take a Payment",
    "iframes/Gateways",
    "Blink pages",
    "Blink Mobile App",
    "Management systems",
  ],
  [
    "processing sales",
    "Request a payment",
    "pre-Authorisation",
    "Verify",
    "Delayed capture",
    "Batch payments",
  ],
  ["Repeat Payments", "Gift Aid"],
  [
    "Reporting & Analysis Overiew",
    "Transaction History",
    "Reports",
    "Scheduled Reporting",
    "Bank Reconcilliation",
  ],
  ["What's included account management"],
  ["What can merchants customise ?"],
];
